apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-demo-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kubernetes-demo
    spec:
      containers:
      - name: kubernetes-demo
        image: kubernetes-demo:0.2 # format: [acr_login_server]:[repository_name]:[tag]
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      app: kubernetes-demo

---

apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-service
spec:
  selector: 
    app: kubernetes-demo
  ports:
    - port: 80
  type: LoadBalancer